import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { apply, emptyJournal, defaults, progress, pattern, total, dayAt, type Journal, type Command } from '../lib/journal.ts';
const now = Date.parse('2026-09-29T12:00:00Z');
const act = (j: Journal, c: Command, t = now) => apply(j, c, randomUUID(), t);
const setup = () => act(emptyJournal(), { type: 'settings', values: { ...defaults, baseline: 10, price: 50, portions: 20 }, effective: '2026-09-01', onboard: true });
const entry = (day: string, n: number, context: null | 'meal' = null) => ({ type: 'entry' as const, entry: { id: randomUUID(), quantity: n, time: day + 'T10:00:00Z', context } });
test('all goals support unknown or zero baselines', () => { for (const goal of ['quit', 'reduce', 'track'] as const) {
    for (const baseline of [null, 0]) {
        const j = act(emptyJournal(), { type: 'settings', values: { ...defaults, goal, baseline }, effective: '2026-09-29', onboard: true });
        assert.equal(j.onboarded, true);
        assert.equal(progress(j, ['2026-09-29']).savings, null);
    }
} });
test('savings fixture includes negative differences; missing days are not zero', () => { let j = setup(); j = act(j, entry('2026-09-27', 6)); j = act(j, { type: 'complete', day: '2026-09-27' }); j = act(j, entry('2026-09-28', 12)); j = act(j, { type: 'complete', day: '2026-09-28' }); assert.deepEqual(progress(j, ['2026-09-27', '2026-09-28', '2026-09-29']), { complete: 2, eligible: 2, savings: 5, average: 9, zeroDays: 0 }); j = act(j, { type: 'complete', day: '2026-09-29' }); assert.equal(progress(j, ['2026-09-29']).zeroDays, 1); });
test('retries do not duplicate an entry or reopen a day twice', () => { let j = setup(); const c = entry('2026-09-28', 1), op = randomUUID(); j = apply(j, c, op, now); j = act(j, { type: 'complete', day: '2026-09-28' }); j = apply(j, c, op, now); assert.equal(j.entries.length, 1); assert.ok(j.completed['2026-09-28']); });
test('edits moving an entry reopen both days and deletion reopens its day', () => { let j = setup(); const c = entry('2026-09-27', 2); j = act(j, c); j = act(j, { type: 'complete', day: '2026-09-27' }); j = act(j, { type: 'complete', day: '2026-09-28' }); j = act(j, { ...c, entry: { ...c.entry, time: '2026-09-28T10:00:00Z' } }); assert.equal(Object.keys(j.completed).length, 0); j = act(j, { type: 'complete', day: '2026-09-28' }); j = act(j, { type: 'remove', id: c.entry.id }); assert.equal(j.completed['2026-09-28'], undefined); });
test('goal changes preserve historical cost basis; effective changes apply forward', () => { let j = setup(); j = act(j, { type: 'settings', values: { ...j.settings, goal: 'quit' }, effective: '2026-09-29' }); assert.equal(j.costs.length, 1); j = act(j, { type: 'settings', values: { ...j.settings, price: 100 }, effective: '2026-09-28' }); for (const d of ['2026-09-27', '2026-09-28'])
    j = act(j, { type: 'complete', day: d }); assert.equal(progress(j, ['2026-09-27']).savings, 25); assert.equal(progress(j, ['2026-09-28']).savings, 50); });
test('patterns need three events on two days; dismissal, pause, and corrections suppress', () => { let j = setup(); j = act(j, entry('2026-09-28', 1, 'meal')); j = act(j, entry('2026-09-28', 1, 'meal')); assert.equal(pattern(j, now), null); const c = entry('2026-09-29', 1, 'meal'); j = act(j, c); assert.equal(pattern(j, now)?.count, 3); j = act(j, { type: 'suggestion', context: 'meal', action: 'shown' }); assert.equal(pattern(j, now)?.shown, true); const corrected = act(j, { type: 'remove', id: c.entry.id }); assert.equal(pattern(corrected, now), null); assert.equal(pattern({ ...j, settings: { ...j.settings, paused: true } }, now), null); j = act(j, { type: 'suggestion', context: 'meal', action: 'dismissed' }); assert.equal(pattern(j, now), null); });
test('timer completion cannot infer consumption or zero-use; premature completion rejected', () => { let j = setup(); const id = randomUUID(); j = act(j, { type: 'session-start', id, exercise: 'delay', context: null }); assert.throws(() => act(j, { type: 'session-end', id, status: 'completed', outcome: 'not-now' })); j = act(j, { type: 'session-end', id, status: 'completed', outcome: 'not-now' }, now + 300000); assert.equal(total(j, '2026-09-29'), 0); assert.equal(progress(j, ['2026-09-29']).zeroDays, 0); });
test('timezone updates preserve old entry assignment', () => { let j = setup(); const c = { ...entry('2026-09-28', 1), entry: { ...entry('2026-09-28', 1).entry, time: '2026-09-28T23:30:00Z' } }; j = act(j, c); assert.equal(j.entries[0].day, '2026-09-29'); j = act(j, { type: 'settings', values: { ...j.settings, timezone: 'America/New_York' }, effective: '2026-09-29' }); j = act(j, { ...c, entry: { ...c.entry, quantity: 2 } }); assert.equal(j.entries[0].day, '2026-09-29'); assert.equal(dayAt(c.entry.time, 'America/New_York'), '2026-09-28'); });
test('future entries and invalid quantities are rejected', () => { const j = setup(); assert.throws(() => act(j, entry('2026-10-01', 1))); assert.throws(() => act(j, entry('2026-09-28', -1))); assert.throws(() => act(j, { type: 'complete', day: '2026-02-31' })); });
