'use client';
import { useState } from 'react';
import { daysEnding, total, progress, type Journal } from '@/lib/journal';
export const sek = (v: number) => new Intl.NumberFormat('sv-SE', { style: 'currency', currency: 'SEK' }).format(v);
export const dateLabel = (d: string) => new Intl.DateTimeFormat('sv-SE', { day: 'numeric', month: 'long', timeZone: 'UTC' }).format(new Date(d + 'T12:00:00Z'));
export function ProgressView({ journal, today, review }: {
    journal: Journal;
    today: string;
    review: (d: string) => void;
}) {
    const [period, setPeriod] = useState(7), days = daysEnding(today, period), stats = progress(journal, days);
    return <><div className="page-heading"><div><p className="eyebrow">VARJE LITET STEG RÄKNAS</p><h1>Dina framsteg.</h1><p>Din historia finns kvar, även efter en svårare dag.</p></div><div className="period-toggle"><button aria-pressed={period === 7} onClick={() => setPeriod(7)}>7 dagar</button><button aria-pressed={period === 30} onClick={() => setPeriod(30)}>30 dagar</button></div></div><div className="stats-grid"><section className="stat-card blue-stat"><p>Uppskattad kostnadsskillnad</p><strong>{stats.savings === null ? '—' : sek(stats.savings)}</strong><span>{stats.savings !== null && stats.savings < 0 ? 'Mer än din angivna baslinje' : 'Jämfört med din angivna baslinje'}</span><small>{stats.eligible} {stats.eligible === 1 ? 'dag' : 'dagar'} med fullständiga prisuppgifter</small></section><section className="stat-card"><p>Snusfria dagar totalt</p><strong>{stats.zeroDays}</strong><span>Alla bekräftade dagar, sedan start</span></section><section className="stat-card"><p>Genomsnitt per dag</p><strong>{stats.average === null ? '—' : stats.average.toLocaleString('sv-SE', { maximumFractionDigits: 1 })}</strong><span>{stats.complete} av {period} dagar bekräftade</span></section></div><section className="chart-card"><div className="section-heading"><h2>Din användning</h2><span className="subtle">Portioner per dag</span></div><div className="chart" role="img" aria-label="Dagliga portioner. Exakta värden och status finns i listan under diagrammet.">{days.map(d => { const n = total(journal, d), max = Math.max(5, ...days.map(x => total(journal, x))); return <div key={d} className="chart-column"><div className="bar-area"><div className={'bar ' + (journal.completed[d] ? 'confirmed' : 'partial')} style={{ height: Math.max(3, n / max * 150) }}/></div><span>{d.slice(8)}</span></div>; })}</div><div className="legend"><span><i className="solid"/> Bekräftad dag</span><span><i /> Ofullständig / saknas</span></div><details><summary>Visa alla dagar och värden</summary><ul className="day-list">{[...days].reverse().map(d => <li key={d}><span>{dateLabel(d)}</span><span>{total(journal, d)} loggade · {journal.completed[d] ? 'bekräftad' : 'ofullständig'}</span><button className="text-button" onClick={() => review(d)}>Granska</button></li>)}</ul></details></section><details className="calculation"><summary>Så räknar vi</summary><p>För varje bekräftad dag: (din baslinje − loggade portioner) × pris per dosa / portioner per dosa. Summan är en uppskattning, inte verifierade pengar på kontot. Ofullständiga dagar räknas inte med. Negativa belopp visar mer användning än baslinjen.</p><p>Pris och baslinje kan ändras i Mitt stöd. Saknas uppgifter visas inget belopp för de dagarna. Snusfria dagar kräver din bekräftelse.</p></details></>;
}
